version: "3.3"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_network
  golang_web:
    build: .
    depends_on:
      - redis
    ports:
      - "8000:8000"
    restart: always
    networks:
      - web_network

networks:
  web_network:
    driver: bridge