version: "3.3"
services:
  redis:
    image: ${DOCKER_REGISTRY}/redis-repository 
    build: ./docker/redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_network
  golang_web:
    image: ${DOCKER_REGISTRY}/web-repository 
    build: ./docker/web
    depends_on:
      - redis
    ports:
      - "8000:8000"
    restart: always
    networks:
      - web_network

networks:
  web_network:
    driver: bridge